spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ms?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
      username: root
      password: root
      max-active: 100
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
        allow:
        deny:
        url-pattern: /druid/*
      test-on-borrow: true
      test-while-idle: true
#配置mybatisplus
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
    #  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
